### ISSUE TITLE
PROSPER.R can error out if GWAS doesn't contain SNPs in the first LD block of a chromosome(?)

### ISSUE THREAD

**Issue by shugamoe** [Jingning-Zhang/PRS-epr#3]
https://github.com/Jingning-Zhang/PROSPER/blob/a3fb3536a0e0983e8a5d1e658d3719634057f142/scripts/PROSPER.R#L316

I noticed this line of code giving me an issue for a single chromosome when trying to use PROSPER.R. It seems like (at least for `i == 1`) the first LD block section (`bl == 1`) of the `res` variable (output of `enet_multiethnic`) can be NULL. My assumption is that maybe the input GWAS don't actually have any variants to compare against the LD reference. So I changed the else section of the code to below.

```
        if (is.null(dim(b_tmp))){
          b_tmp <- tmp1 * tmp2
        } else {
          b_tmp <- rbind(b_tmp, tmp1 * tmp2)
        }
```

After that change, `b_tmp` is able to successfully `rbind` through the rest of the nested loops in that area of code. This just seems to cover the special case where `b_tmp` can't be built when `bl == 1`.

**Comment by Jingning-Zhang** [comment]
Thank you for identifying this bug and providing a solution! I will update the codes accordingly, and put you on acknowledgment.

**Comment by Jingning-Zhang** [comment]
I have updated the code. Please check if it works. Thanks for raising this issue!

**Comment by shugamoe** [comment]
This works, #4 was still an issue for me though and is as well after the fix to this issue.
